services:
  - type: web
    name: fraud-detection-api
    env: python
    region: frankfurt  # or oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
